# backend/storage/interface.py
from __future__ import annotations
from typing import Protocol, runtime_checkable, optional, list
from ..models import Account, Group, Permission, Resource, Role

__all__ = [
    "PermissionRepository", "RoleRepository", "GroupRepository",
    "AccountRepository", "ResourceRepository",
]

@runtime_checkable
class PermissionRepository(Protocol):
    async def add(self, permission: Permission) -> None: ...
    async def get(self, permission_id: str) -> optional[Permission]: ...
    async def list(self, tenant_id: optional[str] = None) -> list[Permission]: ...
    async def delete(self, permission_id: str) -> bool: ...

@runtime_checkable
class RoleRepository(Protocol):
    async def add(self, role: Role) -> None: ...
    async def get(self, role_id: str) -> optional[Role]: ...
    async def list(self, tenant_id: optional[str] = None) -> list[Role]: ...
    async def delete(self, role_id: str) -> bool: ...
    async def assign_permission(self, role_id: str, permission_id: str) -> None: ...
    async def remove_permission(self, role_id: str, permission_id: str) -> None: ...

@runtime_checkable
class GroupRepository(Protocol):
    async def add(self, group: Group) -> None: ...
    async def get(self, group_id: str) -> optional[Group]: ...
    async def list(self, tenant_id: optional[str] = None) -> list[Group]: ...
    async def delete(self, group_id: str) -> bool: ...
    async def assign_role(self, group_id: str, role_id: str) -> None: ...
    async def remove_role(self, group_id: str, role_id: str) -> None: ...

@runtime_checkable
class AccountRepository(Protocol):
    async def add(self, account: Account) -> None: ...
    async def get(self, account_id: str) -> optional[Account]: ...
    async def list(self, tenant_id: optional[str] = None) -> list[Account]: ...
    async def delete(self, account_id: str) -> bool: ...
    async def assign_role(self, account_id: str, role_id: str) -> None: ...
    async def remove_role(self, account_id: str, role_id: str) -> None: ...
    async def assign_group(self, account_id: str, group_id: str) -> None: ...
    async def remove_group(self, account_id: str, group_id: str) -> None: ...

@runtime_checkable
class ResourceRepository(Protocol):
    async def add(self, resource: Resource) -> None: ...
    async def get(self, resource_id: str) -> optional[Resource]: ...
    async def list(self, tenant_id: optional[str] = None) -> list[Resource]: ...
    async def delete(self, resource_id: str) -> bool: ...
